### ISSUE TITLE
cocoonjs doubles the first 200ms of  EVERY sound.. no matter what.. AND cuts of the last 200ms of the audio file

### ISSUE THREAD

**Issue by valueerrorx** [photonstorm/phaser#1431]
i first opened a thread in the forum here:
http://www.html5gamedevs.com/topic/10628-music-loop-in-cocoonjs-the-song-jumps-on-the-first-note-on-every-loop/

ludei gave me the following tip for a fix:
"To fix this issue in Phaser, I'd recommend finding a way to avoid doing pause+play to do the looping, and instead rely on the loop property of the audio objects. I understand this won't work for audio sprites, but for typical background music scenarios it should work fine."

here is the full answer: 
http://www.html5gamedevs.com/topic/3980-common-phaser-cocoonjs-issues/page-13#entry63288

i planned to releas my game with cocoonjs because it has the best performance for now  but this is a showstopper.  is there a way to  do the proposed workaround?

**Comment by photonstorm** [comment]
This is now fixed in the dev branch. Interestingly I *was* using the sound.loop property! But the sound.start parameters were invalidating it.

**Comment by valueerrorx** [comment]
great to hear.. thx..

**Comment by Cristy94** [comment]
I am still having this issue with a background music loop in CocoonJS. The music plays fine, but when it loops the first few notes are played twice. Any fix for that?
