### ISSUE TITLE
[dev] Phaser trying to updateCrop() a preload sprite that doesn't exist anymore. 

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#1636]
..or at least I think that's what's happening. 

I have a Preload.js game state that uses a preload bar with loader.setPreloadSprite(). Once it loads it switches to MainMenu.js which has a "start" button to switch to the main game state. 
When I click on the button the console says:
```
Uncaught TypeError: Cannot read property 'x' of nullphaser.js:34381
Phaser.Component.Crop.updateCrop phaser.js:55830
Phaser.Loader.updateProgressphaser.js:54849 Phaser.Loader.start phaser.js:18040
Phaser.StateManager.preUpdatephaser.js:26223 Phaser.Game.updateLogic phaser.js:26172
Phaser.Game.updatephaser.js:43967 Phaser.RequestAnimationFrame.updateRAF phaser.js:43951
_onLoop
```

The line it refers to is <code>this._crop.x += this._frame.x;</code> inside Phaser.Component.Crop.updateCrop

I added a breakpoint to that line and the value of this.key is "preloadBar", the preload sprite I set before. So I think it's still trying to update a preload sprite that doen't even exist anymore. 

If I comment the code that sets the preload sprite the game runs fine(well, collision doen't work, but that's an unrelated bug that has already been reported).

I'm using the latest ( 46c6a86e065b15d8c84cbaeb07a412a2c79aa2b4 ) phaser-arcade-physics.js built with grunt arcadephysics. But it's been happening in many previous builds.

**Comment by noidexe** [comment]
Apparently the bug was introduced in 8d614418444a1db305adc9a895f51ef19530c296

**Comment by photonstorm** [comment]
I think what's more interesting is that it's still trying to update what should be a now dead sprite. Either way I'll look into this tonight.

**Comment by photonstorm** [comment]
Ok this should now be fixed in dev, please give it a bash and reopen if not! (physics too btw :))

**Comment by noidexe** [comment]
I still get the same error. 
```
           if (this.preloadSprite.sprite)
           {
               this.preloadSprite.sprite.updateCrop();
           }
           else
           {
               //  We seem to have lost our sprite - maybe it was destroyed?
               this.preloadSprite = null;
           }
```
this.preloadSprite.sprite returns true because the sprite still exists(though I think it shouldn't since it was created in another game state).

<code>this._crop.x += this._frame.x; </code> 
Here this._frame is null so it doesn't have any x property and that's what the vm is complaining about "Uncaught TypeError: Cannot read property 'x' of null"

I think the problem is that preloadSprite.sprite is not being destroyed when there is a game state change.

**Comment by photonstorm** [comment]
Hmm it's because Loader.reset() needs `true` as the first parameter, but a simple state swap won't do that, so the preloadSprite is never removed. A state swap will never *destroy* a sprite anyway (that is your responsibility), but I think it'd make sense if Loader.reset cleared the preloadSprite object out.

**Comment by noidexe** [comment]
I didn't know you could do that and It was never necessary before so I thought it was a bug. 

Ok, with the same build of phaser I was using in the last comment, I did <code>this.load.preloadSprite = null;</code> before swaping states and it worked. 

Using the last build of phaser it works just fine without changing any code. Thanks!
