### ISSUE TITLE
Phaser.Polygon.prototype.contains is looking for points with x & y properties, where as points are defined as a flat array. It means the hit test on graphics objects doesn't work.

### ISSUE THREAD

**Issue by Tetley** [photonstorm/phaser#1779]
Phaser.Polygon.prototype.contains is looking for points with x & y properties, where as points are defined as a flat array. It means the hit test on graphics objects doesn't work.

![phasergraphics](https://cloud.githubusercontent.com/assets/587241/7489581/3eb68166-f3d0-11e4-802b-75d96ab52f02.jpg)

![phasergraphics1](https://cloud.githubusercontent.com/assets/587241/7489597/6cc0398a-f3d0-11e4-80f9-527039bbb390.jpg)

**Comment by photonstorm** [comment]
Which version of Phaser is this? because in the current (2.3 + dev) _points is an array of points and the geometry / polygon contains example is working.

Having said that, if you were to call polygon.flatten() then it would change the shape of the _points array to be a flat list of numbers. But aside from doing this, it should always contain Point objects.

**Comment by Tetley** [comment]
Using Version 2.3.0. I don't explicitly call polygon.flatten(), it is however called by PIXI.Graphics.prototype.drawShape which is called by moveTo() on my Phaser.Graphics instance. The geometry / polygon example uses Phaser.Graphics.drawPolygon(), so I'm going to switch to that method, which I'm sure will work. Thanks

**Comment by photonstorm** [comment]
To be honest I dislike the way Pixi.Graphics manages drawing objects. It creates new geometry objects every time it's updated and fails to be able to take geometry objects and render them in several cases. I fully intend to go through the class and sort it out at some point soon, which will ensure I remove the polygon.flatten call too.

**Comment by photonstorm** [comment]
Hi - this should now be fixed in the dev branch - would be good if you could test.

**Comment by Tetley** [comment]
I did work around this issue using the polygon contains method, as opposed to game.input.hitTest on the graphics instance. This is an example of what I was originally doing, that still doesn't work on the dev branch.

```javascript
var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { create: create, update: update, render: render });
var graphics;
var hit = false;

function create() {
    graphics = game.add.graphics(0, 0);

    graphics.beginFill(0xFF33ff);
    graphics.moveTo(200,100);
    graphics.lineTo(350, 100);
    graphics.lineTo(375, 200);
    graphics.lineTo(150, 200);
    graphics.endFill();
}

function update() {
    if(game.input.hitTest(graphics, game.input, new Phaser.Point())){
        hit = true;
    }else{
        hit = false;
    }
}

function render() {
    game.debug.text(game.input.x + ' x ' + game.input.y + ' hit=' + hit.toString(), 32, 32);
}
```

This code works when pasted into the "polygon contains" example - (http://phaser.io/examples/v2/geometry/polygon-contains#gv)

Which had me confused as it wasn't working for me when I raised the issue, I then noticed that when you run code using the "Phaser Example Runner" it loads version 2.2.2 (which may be another slight issue, see the bottom screenshot). So it must have broke in 2.3.0.

Hopefully this helps. I also tested the polygon.contains method (that I'm now using) on the dev branch and it works.

![phaser example runner](https://cloud.githubusercontent.com/assets/587241/7713171/f80dbb14-fe6d-11e4-8257-2ce4814a8e4c.PNG)

**Comment by photonstorm** [comment]
I'm amazed input.hitTest _ever_ worked on a Graphics instance! I'm guessing the old version of Pixi supported it maybe. Will have a deeper look when I get time, but at least polygons should no longer get flattened by just rendering them any more.
