### ISSUE TITLE
Changing text property of tinted BitmapText doesn't use correct glyphs

### ISSUE THREAD

**Issue by Pajamaman** [photonstorm/phaser#1969]
Add a BitmapText to the game and give it a tint:

```javascript
var game = new Phaser.Game(320, 200, Phaser.AUTO, '', {preload: preload, create: create}),
    text;

function preload() {
    game.load.bitmapFont('desyrel', 'desyrel.png', 'desyrel.xml');
}

function create() {
    text = game.add.bitmapText(0, 0, 'desyrel', 'bar', 64);
    text.tint = 0x55ff55;
}
```

Once the page loads, type this in the console:

```javascript
text.text = 'foobar';
```

Result:

![image](https://cloud.githubusercontent.com/assets/1323271/9027853/2c8f5d90-3922-11e5-8944-99d3d42699d8.png)

As a workaround, you can type this in the console after setting the text:

```javascript
text.removeChildren();
text.purgeGlyphs();
```

Correct result:

![image](https://cloud.githubusercontent.com/assets/1323271/9027861/96833d0c-3922-11e5-820a-9d5b18e29232.png)

I'm using Phaser 2.4.2 and Chromium 43.0.2357.130 Ubuntu 14.04 (64-bit).

**Comment by Cristy94** [comment]
I think text is read only, and you should use text.setText('foobar') instead. http://phaser.io/docs/2.3.0/Phaser.BitmapText.html#setText

**Comment by Pajamaman** [comment]
Same result with `setText()`.

**Comment by Cristy94** [comment]
What about calling `.updateText()` after you set it?

**Comment by Pajamaman** [comment]
`.updateText()` is called by the `text` property setter. In other words, nope.

**Comment by photonstorm** [comment]
Actually I think it's directly related to this: https://github.com/photonstorm/phaser/commit/9362a2b1f480ef570c2a5a05e2fceec03e169262

**Comment by photonstorm** [comment]
This is now fixed in a dev - and didn't require anything as intense as any of the suggestions above thankfully :)

**Comment by Pajamaman** [comment]
Oh, hah. That's much simpler indeed. Thanks for the speedy fix!

**Comment by DDowell** [comment]
I still get it in 2.6.1 albeit not as frequent. I first had the setText outside of the phaser game loop but even after moving it into the game loop, it happens from time to time.
