### ISSUE TITLE
Failed to execute 'start' on 'AudioBufferSourceNode'

### ISSUE THREAD

**Issue by Weedshaker** [photonstorm/phaser#2351]
Hello,

I get this error:

_Uncaught InvalidStateError: Failed to execute 'start' on 'AudioBufferSourceNode': The offset provided (-29.173) is less than the minimum bound (0)._

 since updated to 2.4.6 when resuming sound. I guess it may could be fixed with a simple check on the variable set to start. var < 0 ? 0 : var. But I don't know where.

THX

**Comment by photonstorm** [comment]
Thanks, fixed in dev.

**Comment by Weedshaker** [comment]
Cool! THX

**Comment by QuipHop** [comment]
I still facing this issue on phaser + cordova (but only on Meizu phones)
Does anybody know what can it be ?
