### ISSUE TITLE
Fonts with digits in the name don't work

### ISSUE THREAD

**Issue by And-0** [photonstorm/phaser#2390]
I tried to use the font 'Press Start 2P' for ingame text but it didn't work, neither locally nor via Google Webfonts. The text was never displayed in the right font and instead fell back to Arial. After ruling out loading issues and experimenting a bit, I noticed that this issue seems to be present for all fonts with a digit in the name (another example would be the font 'Slabo 13px').

However, if I changed the font of a text object _after_ creating it as follows:

    var txt = game.add.text(0,0,"Foo");
    txt.font = "Press Start 2P";

then the font was displayed correctly.

After digging around Text.js a bit I think I found the reason: In the function `Object.defineProperty` the font string is quoted (if it isn't already) while in `Phaser.Text.prototype.componentsToFont` this is not the case. Once I added a line to `Phaser.Text.prototype.componentsToFont` that quotes the `fontFamily` property, all fonts work right away.

I can't say for sure why the quotes make the difference here, but it fixed the problem for me. If this indeed a bug and my fix doesn't mess up anything else (my tests went well, but I don't know the codebase all that well) I'd be happy to create a pull request!

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by BeFiveINFO** [comment]
I am afraid that the issue still appears to persist as of Phaser v3.15.1.

https://labs.phaser.io/edit.html?src=src\game%20objects\text\static\google%20webfont.js

Setting the press start 2p font in the above example as:

```
        google: {
            families: [ 'Press Start 2P', 'Finger Paint', 'Nosifer' ]
        },
....
           add.text(16, 0, 'The face of the\nmoon was in\nshadow.', { fontFamily: 'Press Start 2P', fontSize: 80, color: '#ffffff' }).setShadow(2, 2, "#333333", 2, false, true);
 
```
Results as 

![screen shot 2018-11-23 at 14 02 12](https://user-images.githubusercontent.com/2150168/48947258-66f71800-ef28-11e8-980d-76fa1aebd6ce.png)

**Comment by BeFiveINFO** [comment]
I am very sorry, I did not know that this issue was for Phaser 2. I will keep that in mind.

**Comment by photonstorm** [comment]
Just to say that fonts with numbers in the name will work fine as long as you quote them, i.e. `{ fontFamily: '"Press Start 2P"', ...` just as you would have to in CSS.
