### ISSUE TITLE
phaser/typescript/typings.json is not a module

### ISSUE THREAD

**Issue by donaldpipowitch** [photonstorm/phaser#2746]
This Issue is about (delete as applicable)
- An error in the TypeScript defs

When using `typescript@next` I get `phaser/typescript/typings.json is not a module`. This probably happens because of this line: https://github.com/photonstorm/phaser/blob/master/package.json#L51
I never saw someone linking to the `typings.json`. I think this must be linked to a `.d.ts`.

Other errors I get: `phaser/typescript/typings.json(2,11): error TS1005: ';' expected.`

**Comment by hccampos** [comment]
Same error here.

**Comment by wingyplus** [comment]
From this [link](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html), `"typings"` in package.json should be `"./typescripts/phaser.comments.d.ts"`.

**Comment by photonstorm** [comment]
Sure, go for it. Anything to get bloody TS working. Honestly, I must waste so much time looking after defs, etc. Am honestly _this_ close to just dropping them from the repo, and letting someone else deal with it.

**Comment by donaldpipowitch** [comment]
Oh no, please not. Keep it in the package. In my experience it is not that hard to maintain. What are your problems with it?

You typically just have a `"typings"` field your `package.json` pointing to a `.d.ts`. And the `.d.ts` is quite simple. And _if_ there should be something which is too complicated to express in TypeScript you can just give it the type `any` as an escape hatch.

**Comment by photonstorm** [comment]
Trust me, there is nothing simple about having to maintain a 5700+ line Phaser defs file and a 2000 line Pixi defs, and ensure they are in sync with a constantly evolving Phaser API. And then things like TS 2 come along and cause havoc with its new strict setting, etc :(

**Comment by donaldpipowitch** [comment]
I know... Your project is big! Definitely. But despite stricter settings in TS2 (which are really useful for finding bugs!) the big problem here isn't the complexity of the format, but staying in sync with the source files, right?

Did you tried to generate declaration files from your JSDocs comments? Looks like you use them a lot. Or did you considered switching phaser itself to TypeScript? You should try make a small private project with TypeScript 2 and a modern IDE like VS Code: code completion, refactoring, inline documentation and so on work really well nowadays. Especially such a big project like phaser itself would benefit from being written in TypeScript.

**Comment by hilts-vaughan** [comment]
Phaser used to be written in TypeScript but was changed to JS at some point.

**Comment by donaldpipowitch** [comment]
Me, too. Converted some TS projects to JS. We looked multiple times into TS, but I always thought it has more downsides than upsides. But many are fixed by now... The TS team did a really great job. We just switched to TS some month ago.

**Comment by mredbishop** [comment]
We have written and currently maintain a line of business system that is 210k+ lines written in typescript with a number of API's that we provide external typings for. It was a real pain in the ass to start with, due to all the constant changes etc until earlier this year but over the last 6 months or so it has really turned into a solid language. As of the current version there is absolutely no way I would write a large system of any kind in plain JavaScript and I don't believe there is anything I could do in JS that I cannot do in TS.

We use Typescript 2, VS Code (most of the team use the insiders build) and npm as our task runner (see https://medium.freecodecamp.com/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8 for good reasons why). It's incredibly productive and, although this may not be so important here, a massive time saver when it comes to integrating other peoples code into a project.

**Comment by Aristona** [comment]
@wingyplus I'm still getting the same error despite adding `"typings": "./typescript/phaser.comments.d.ts",` to my package.json file. Is there anything I can do about it?

**Comment by donaldpipowitch** [comment]
@Aristona This line should not be added to _your_ `package.json`, but phasers.

I haven't used phaser in a while so I don't know what is the current state of this issue.

**Comment by Aristona** [comment]
@donaldpipowitch Oh, okay. That solved the issue. Is there any way to fix it without changing Phaser's package.json? That'll be overridden when I issue a npm install.

**Comment by donaldpipowitch** [comment]
We probably need to make a PR to phaser, but I have no idea what is the state of phaser and v3. It still has a `"typescript"` keyword in its `package.json` (see [here](https://github.com/photonstorm/phaser/blob/master/v3/package.json#L29)), but it looks like the TypeScript folder was removed and the source code isn't written in TypeScript. So v3 will probably remove TypeScript support at all...? Would be sad to see this.

**Comment by WaveFunctionP** [comment]
I don't know if I'm doing something wrong, or if phaser has an issue

One of the reasons I chose Phaser was support for typescript. Documentation can always be spotty, but being able to . your way to glory and check signatures is very useful.

I've been unable to get intellisense working for phaser. AFAIK, typescript should be able to find the definitions in node_modules if I add it to my project.json since ts2. But it doesn't. And @types doesn't work either.

http://stackoverflow.com/questions/38444279/how-should-i-use-types-with-typescript-2

**Comment by photonstorm** [comment]
The PR should be against the Phaser CE repo: https://github.com/photonstorm/phaser-ce

Phaser 3 will have TS defs, yes. They're being worked on at the moment.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
