### ISSUE TITLE
Invalid link to zip file in  https://phaser.io/tutorials/getting-started/part6

### ISSUE THREAD

**Issue by iamropo** [photonstorm/phaser#2886]
https://github.com/photonstorm/phaser/raw/master/resources/tutorials/01%20Getting%20Started/hellophaser.zip

**Comment by iamropo** [comment]
reporting the issue in the comment section of the page

**Comment by photonstorm** [comment]
This is now fixed. It's due to the huge repo change we made the other day.

**Comment by GodotIsAMess** [comment]
I just reported this https://rawgit.com/photonstorm/phaser/dev/build/phaser.js 404 error page far before @iamropo and it's not fixed yet. Please stop showing favouritism

**Comment by photonstorm** [comment]
Just a heads-up but your comments are starting to get too personal. Keep
them in check please.
