### ISSUE TITLE
`GlobalStateManager#add` not assigning key to state class or function.

### ISSUE THREAD

**Issue by rblopes** [photonstorm/phaser#3029]
This issue is about a bug in Phaser v3 API.

Phaser always assign `default` as the state key when passing `GlobalStateManager#add` the desired key and state class (or function).

Example:
```javascript
class Test extends Phaser.State {
    create() {
        // Should output "This state key is test."
        console.log(`This state key is ${this.state.key}.`);
    }
}

const game = new Phaser.Game({
    parent: 'phaser-example',
    width: 320,
    height: 240,
});

game.state.add('test', Test, true);
```

![spectacle j12093](https://user-images.githubusercontent.com/61425/27771296-621eb406-5f22-11e7-84b3-90584fe06c7d.png)

**Comment by photonstorm** [comment]
Well spotted. This is now fixed in master.

**Comment by rblopes** [comment]
The bug is still there, sorry. If the state class is not deriving from `Phaser.State`, it works fine, the console prints the right state key. The example code still fails, however.

`GlobalStateManager#add` delegates to `createStateFromFunction` method, where the key parameter is [overwritten][0] ─ for some reason, the instantiated state still gets the `default` key.

[0]: https://github.com/photonstorm/phaser/blob/b3a9b2bed83bd6c13fa6c503512c6b85ce54ae13/v3/src/state/GlobalStateManager.js#L228-L238

**Comment by photonstorm** [comment]
This now passes.
