### ISSUE TITLE
Error with TileMap sprite rendering in WebGL (3.1.1)

### ISSUE THREAD

**Issue by akleemans** [photonstorm/phaser#3266]
This Issue is about:
* A problem with my own code OR
* A bug in the API - Phaser 3.1.1

First off, thanks for the great work and the Phaser 3 release, really exciting to build a game with it!
I just updated from 3.1.0 to 3.1.1 and am experiencing problems with the WebGL rendering. I started working on a game which uses TileMaps some weeks ago.

When I updated from 3.1.0 to 3.1.1 just an hour ago, my game stopped working correctly and now all Tiles are painted black. I'm using a TileMap with TileSprites designed in Tiled, which I imported into Phaser, and it worked until 3.1.0.

I tried to strip it down to a minimal example, and tested it with both the 3.1.0 / 3.1.1 versions and the Phaser.CANVAS / Phaser.WEBGL configurations:

* Example with 3.1.0 / canvas, WebGL - **working**: [Link](https://www.kleemans.ch/static/awesome-game/bug-webgl-310/)
* Example with 3.1.1 / canvas - **working**: [Link](https://www.kleemans.ch/static/awesome-game/bug-canvas-311/)
* Example with 3.1.1 / WebGL - **not working**: [Link](https://www.kleemans.ch/static/awesome-game/bug-webgl-311/)
 
Code: [Link](https://www.kleemans.ch/static/awesome-game/bug-webgl-311/main.js)
(I tried making a CodePen, but couldn't load any assets due to the blocked cross-origin requests, sorry.). I am trying to load [this Tiled JSON Tilemap](https://www.kleemans.ch/static/awesome-game/bug-webgl-311/assets/tilemaps/maps/level0.json) with [this Tileset image](https://www.kleemans.ch/static/awesome-game/bug-webgl-311/assets/tilemaps/tiles/platformer_tiles.png).

In WebGL with 3.1.1, instead of TileMaps and sprites I get a black background. Suprisingly the player sprite, which is loaded separately, works as intended. I stripped out all animations and unused objects, but it's still not showing the TileMap tiles in WebGL. The rest of the game seems to work (rendering, camera, input), it's really just the Tiles that aren't showing up.

I get the following errors in the console (in Firefox 59.0 and Chrome 64):

> Error: WebGL warning: vertexAttribPointer: If ARRAY_BUFFER is null, byteOffset must be zero.
> phaser.js:25432:17
> Error: WebGL warning: drawArrays: Vertex attrib array 0 is enabled but has no buffer bound.
> phaser.js:46267:13
> Error: WebGL warning: vertexAttribPointer: If ARRAY_BUFFER is null, byteOffset must be zero.
> phaser.js:25432:17
> Error: WebGL warning: drawArrays: Vertex attrib array 0 is enabled but has no buffer bound.
> phaser.js:46267:13
> Error: WebGL warning: vertexAttribPointer: If ARRAY_BUFFER is null, byteOffsett must be zero.
> phaser.js:25432:17
> Error: WebGL warning: drawArrays: Vertex attrib array 0 is enabled but has no buffer bound.
> phaser.js:46267:13
> ...

Any ideas why this could be the case? I can set the type to Phaser.CANVAS (in the configuration, see the examples above), but I think it should also work with Phaser.AUTO. I tried looking into the Phaser source code but unfortunately I don't understand what is going on at the lines mentioned, that's why I thought I'll open an issue :-) 

Please note that this is my first issue, I'd be glad to provide more information if needed.

**Comment by akleemans** [comment]
I guess this is related to the Tiled JSON map example, which is also giving the same errors:
http://labs.phaser.io/view.html?src=src\game%20objects\tilemap\static\tiled-json-map.js

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by akleemans** [comment]
@photonstorm I tested with the latest `master` and it's working again. Thanks for fixing!

**Comment by ivansychev** [comment]
@photonstorm it looks like the issue is still present if you use OS Chrome. Mine is version 66.0. 

Even when I open this example on Mac http://labs.phaser.io/view.html?src=src\game%20objects\tilemap\static\tiled-json-map.js&v=dev version 3.11.0 has black painted tiles, but v3.10 works fine.

**Comment by photonstorm** [comment]
Above examples work fine in Chrome on OS X for me, both in the 3.12 dev build and 3.11. This issue is 6 months old now. If you can reproduce this across more than just your Mac, then open it as a new issue and we can investigate.
