### ISSUE TITLE
Starting a paused tween does not work

### ISSUE THREAD

**Issue by jazen** [photonstorm/phaser#3452]
This Issue is about

* A bug in the API (using `3.3.0`)

I'm trying to create a `paused` tween and start it on `pointerdown`:

```
  // Doesn't really matter just some properties
  const x = {
    duration: 4000,
    ease: 'Sine.easeInOut',
    flipX: true,
    repeat: -1,
    value: 700,
    yoyo: true,
  }

  const props = {
    targets: [sprite],
    x,
    paused: true, // <-- Starting in paused state
  }

  const tween = this.tweens.add(props)

  sprite
    .setInteractive()
    .on(`pointerdown`, pointer => {
      if (tween.isPlaying()) {
        tween.pause()
      } else {
        tween.resume() // <-- Does not start/resume the tween?
      }
    })
```

Interestingly it works if I remove the `paused` property and create the tween conditionally in the `pointerdown` handler (and immediately pause it):

```
  const props = {
    targets: [card],
    x,
    // paused: true,  <-- Removed
  }

  let tween = null;

  card
    .setInteractive()
    .on(`pointerdown`, pointer => {
      tween = tween || this.tweens.add(props) // <-- Create here if not done yet

      if (tween.isPlaying()) {
        tween.pause() // <-- Playing now, so pause it immediately
      } else {
        tween.resume()
      }
    }
```

Am I misunderstanding something or is this behaviour not expected?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by jazen** [comment]
Thank you :)

**Comment by jbromberg** [comment]
I'm still having this issue. If the tween starts paused, it doesn't resume. It only works if it isn't started paused and is then paused and resumed later.
