### ISSUE TITLE
Arcade body not setting "blocked" to true when being stopped by static body

### ISSUE THREAD

**Issue by fariazz** [photonstorm/phaser#3691]
Not sure if this is expected behavior, but if an Arcade body is being stopped by a static / immovable body, its `blocked` property doesn't turn to true. `touching` on the other hand turns to true.

Feel free to discard if disagree, conceptually I think a floor or wall created with Tiled should be equivalent to a blocking element that has been manually placed in the level.

**Comment by hexus** [comment]
I agree, blocked should be being set here. I wonder how this compares with Phaser 2 behaviour.

**Comment by samme** [comment]
`collide` or `overlap` of two Arcade Bodies always sets `touching.*`, never `blocked.*`.

`blocked.*` is set only by Body vs. TilemapLayer or Body vs. world bounds.

**Comment by photonstorm** [comment]
Yes, as @samme said - I guess the difference is that in v2 there was no such thing as a static body. So for v3 we could consider those as being similar to tilemaps (which are also static bodies in their own way)

**Comment by samme** [comment]
You can also `overlap` against a Phaser 3 StaticBody, though. Would that be blocked or touching?

**Comment by hexus** [comment]
I feel like `blocked` should be set when the body is unable to move in that direction, and `touching` should be set when the collision response is in that direction (`dot > 0`) but the body is still able to move on that axis.

That's how my slopes plugin works, at least. :)

**Comment by fariazz** [comment]
> You can also overlap against a Phaser 3 StaticBody, though. Would that be blocked or touching?

That is a good point, didn't think of that.

**Comment by photonstorm** [comment]
If they overlapped it wouldn't set blocked anyway, because it didn't happen as part of the separation - I think it should be safe to make this change. It would also allow you to do things like an `onFloor` check with a dynamic body standing on a static one.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by fariazz** [comment]
Thanks @photonstorm ! Just tested it and it works on my end.

**Comment by samme** [comment]
I'm still seeing `blocked.none === true` after collisions with static bodies: <https://codepen.io/samme/pen/pKpEmQ>

**Comment by sergei202** [comment]
I'm having a similar issue and can't seem to find the reason for it.  It's a simple Bomberman clone game with tiles.  Using Phaser v3.10.1.

`player.body.blocked` or `player.body.touching` never gets set for:
   - World bounderies
   - Tiles
   - Other arcade spires

![image](https://user-images.githubusercontent.com/15058464/42606571-04ef99dc-8544-11e8-9e24-aec2ca846e4d.png)

Live version: https://sergei202.com/bomberman/
Code: https://github.com/sergei202/bomberman

Any help or pointers would really be appreciated!

**Comment by sergei202** [comment]
Looks like my problem was trying to use `body.blocked` and `body.touching` inside of an `update()` instead of inside a `collider()` callback.

**Comment by hexus** [comment]
In @samme's case, I'd still expect blocked to stay `true` within the update loop because he's calling `collide()`, and one might even expect that to stay the same even with a `collider()` set up.
