### ISSUE TITLE
Sprites added to containers do not animate correctly unless added to the scene as well

### ISSUE THREAD

**Issue by halgorithm** [photonstorm/phaser#3876]
*Phaser version:* 3.11.0
*Code example:* http://jsfiddle.net/7od1qk26/8/

*Expected behavior:* If a sprite is added to a container and its container is added to the scene, the sprite should display and animate correctly.

*Actual behavior:* Sprites will only animate correctly if they are added directly to the scene, even if their container was already added to the scene. Otherwise, the sprite displays the first frame of the requested animation and then gets stuck.

*Similar issues:* #3773

**Comment by photonstorm** [comment]
Add this to the long list of reasons why Containers ought to be redone from scratch.

**Comment by Jonnypeng** [comment]
```
let cube = this.add.sprite(400,300,"cube");
 //let cube = new Phaser.GameObjects.Sprite(this,400,300,'cube');
 layer.add(cube);
```
so write can run

**Comment by gogoprog** [comment]
This is quite a huge issue, I spent too much time trying to figure out why my animations were not played.

Could you add a warning somewhere while it is not fixed? (in code or docs)

**Comment by samme** [comment]
Isn't this expected? Containers aren't in the scene update list at all.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by lyger** [comment]
I'm still experiencing this issue in 3.54.0 (in fact, changing the version to 3.54 in the jsfiddle originally linked shows the same problem).

**Comment by willypoon** [comment]
Hello, I have faced the same issue that the sprite inside the container cannot show animation correctly on 3.55.1 too. Are there  any other solutions instead of adding them on the scene directly too ? thank you.

**Comment by 0ffero** [comment]
Yeah, this is still broken as mentioned by Iyger above. Tested in 3.55.2

**Comment by Corso02** [comment]
> ```
> let cube = this.add.sprite(400,300,"cube");
>  //let cube = new Phaser.GameObjects.Sprite(this,400,300,'cube');
>  layer.add(cube);
> ```
> 
> so write can run

for anyone who has stumbled upon this thread, this solved my problem

**Comment by photonstorm** [comment]
This was fixed in 3.60 Beta 9, released yesterday.
