### ISSUE TITLE
RequestAnimationFrame stop() method is not working during scene update and render

### ISSUE THREAD

**Issue by tolimeh** [photonstorm/phaser#3952]
## Version
* Phaser Version: Phaser 3.11
## Description

RequestAnimationFrame.js

    stop: function ()
    {
        this.isRunning = false;

        if (this.isSetTimeOut)
        {
            clearTimeout(this.timeOutID);
        }
        else
        {
            window.cancelAnimationFrame(this.timeOutID);
        }
    },

window.cancelAnimationFrame(this.timeOutID) does not break the requestAnimationFrame loop and stop if it is called during the scene update and render process. The reason for this is this.timeOutID is not pending anymore.  Frame is available and a next frame hasn't been requested yet. Since there is no pending frame request at that moment, there is nothing to cancel.

        this.step = function step (timestamp)
        {
            // DOMHighResTimeStamp
            _this.lastTime = _this.tick;

            _this.tick = timestamp;

            _this.callback(timestamp);

            _this.timeOutID = window.requestAnimationFrame(step);
        };

To break the loop and stop, window.requestAnimationFrame(step) may be called only after checking if this.isRunning is true,

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by garkin** [comment]
I still get this issue in 3.19. Looks like it was rolled back in https://github.com/photonstorm/phaser/commit/4681bb888d574b485ce0ab405031ac6e31f9c437 

Following patch should help:
```diff
this.step = function step ()
{
+    /* FIX https://github.com/photonstorm/phaser/issues/3952 */
+    if (!_this.isRunning) 
+    {
+        return;
+    }

    //  Because we cannot trust the time passed to this callback from the browser and need it kept in sync with event times
    var timestamp = window.performance.now();

    //  DOMHighResTimeStamp
    _this.lastTime = _this.tick;

    _this.tick = timestamp;

    _this.callback(timestamp);

    _this.timeOutID = window.requestAnimationFrame(step);
};
```

**Comment by garkin** [comment]
Better way.
```diff
this.step = function step ()
{
    //  Because we cannot trust the time passed to this callback from the browser and need it kept in sync with event times
    var timestamp = window.performance.now();

    //  DOMHighResTimeStamp
    _this.lastTime = _this.tick;

    _this.tick = timestamp;

    _this.callback(timestamp);

-    _this.timeOutID = window.requestAnimationFrame(step);
+    /* FIX https://github.com/photonstorm/phaser/issues/3952 */
+    if (_this.isRunning) 
+    {
+        _this.timeOutID = window.requestAnimationFrame(step);
+    }
};
```

**Comment by vzhou842** [comment]
This issue still occurs today (`v3.55.2`), would be nice for it to be fixed but I can resolve it a different way on my end
