### ISSUE TITLE
Spine plugin throws error on resize

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4808]
## Version

* Phaser Version: 3.20.0

* Operating system: Windows 10

* Browser: Google Chrome

## Description

Spine plugin throws error on canvas resize.
## Additional Information

![image](https://user-images.githubusercontent.com/30594036/66900515-02e0b500-f00e-11e9-968f-bff061ca2f14.png)

Game.ts
```
import { gameConfig } from './constants/GameConfig';
import GameFacade from './GameFacade';
import { generateGameConfiguration } from './utils/Utils';

export default class Game extends Phaser.Game {
  constructor() {
    super(generateGameConfiguration());
    window.onresize = this.resize.bind(this);
    this.resize();
  }

  public resize(): void {
    const { width, height } = this.config as any;

    const scale: { x: number; y: number } = {
      x: (window.innerWidth || width) / width,
      y: (window.innerHeight || height) / height,
    };
    const browserScale: number = Math.min(
      window.innerHeight / height,
      window.innerWidth / width,
    );
    scale.x = scale.y = browserScale;
    this.canvas.style.position = 'absolute';
    this.canvas.style.width = width * scale.x + 'px';
    this.canvas.style.height = height * scale.y + 'px';
    this.canvas.style.left = 0 + 'px';
    this.canvas.style.top = 0 + 'px';
    this.input.scaleManager.setGameSize(
      gameConfig.canvasWidth,
      gameConfig.canvasHeight,
    );
  }
}
```

I've done some checks, and found out that this happens with scenes, that have been added to game and then removed.  `SpinePlugin` instance will listen to canvas resize and crash.

Destroying `SpinePlugin` before removing scene `this.spine.destroy()`, throws error
![image](https://user-images.githubusercontent.com/30594036/66902717-29a0ea80-f012-11e9-8c31-20ccfab0b224.png)

Removing `SpinePlugin` before removing scene doesn't take an effect. It still listening to 'resize' event.

**Comment by RollinSafary** [comment]
I've done some checks, and found out that this happens with none active scenes, that have been added to game but haven't started yet.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

In the meantime, you can use the command `npm plugin.spine.full.dist` to build a new version of the plugin. It doesn't require a new build of Phaser as well, only of the plugin.

**Comment by RollinSafary** [comment]
@photonstorm bug isn't fixed. Still listening to resize event.

**Comment by photonstorm** [comment]
Did you actually test it with a rebuilt Spine plugin? As this isn't part of 3.21, it's separate from that.

**Comment by RollinSafary** [comment]
My fault will try that tomorrow

**Comment by RollinSafary** [comment]
Worked, thanks a lot.

**Comment by photonstorm** [comment]
Alright, neat. I'll make sure the Spine plugin is republished once I've finished updating it for the new runtimes.
