### ISSUE TITLE
setOrigin on bitmaptext is odd/incorrect

### ISSUE THREAD

**Issue by thenonamezz** [photonstorm/phaser#5121]
## Version

* Phaser Version: 3.21.0 - 3.23.0

* Operating system: Windows 10

* Browser:

## Description

When using setOrigin it should set the middle to be at the middle of the bitmaptext, it technically(?) does, but it doesn't seem to set it correctly.

Edit:
If you put it in a container and scale the container to (-1,1) then it correctly flips

## Example Test Code

https://labs.phaser.io/view.html?src=src\game%20objects\bitmaptext\static\text%20origin.js

Versions from 3.21.0 to newest isn't working correctly, 3.20.1 works as intended
Can be tested further by trying to flip the bitmaptexts with scaling it to (-1,1)

**Comment by Aveyder** [comment]
Can confirm this issue. Probably this bug appeared after BitmatText wrapping feature had implemented. As I can see BitmapText.getTextBounds() method has changed, is it possible that this change could caus this odd setOrigin behaviour?

**Comment by photonstorm** [comment]
Looking at this further, the origin is actually correct. The text is appearing exactly where it should do in the example linked above, regardless of which version you pick.

The issue is that the values the `getTextBounds` function returns is correct in 3.20 and wrong in 3.21+. If you look at the example you'll see the text itself never changes place, it's only the bounds rectangle that does.

Will have a look to see why that is happening. If you have an example showing how the text itself is misplaced (not just the bounds) then I'd like to see it, please.

**Comment by photonstorm** [comment]
Changing the origin of a BitmapText will now flag it as being dirty, allowing things like `getTextBounds` to recalculate the values correctly.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by thenonamezz** [comment]
It still doesn't seem correct, by adding the code at https://pastebin.com/hf9f5E7u at the end of the create function in the example added at the start (https://labs.phaser.io/edit.html?src=src/game%20objects\bitmaptext\static\text%20origin.js) you can see that it flips over and around the origin but ending at the position if it flipped over the middle left point

**Comment by photonstorm** [comment]
This works fine in 3.50, leaving it as closed.

**Comment by thenonamezz** [comment]
On Phaser version 3.25.0-beta.0 inserting this code https://pastebin.com/HMuCLHVL doesn't do what it's supposed to do according to me, it should;
1. create a bitmaptext object with the text "Phaser 3"
2. set the bitmaptext origin to the middle (0.5,0.5)
3. set the bitmaptext to be interactive
4. set so that when you click on it, it should then flip it over the middle Y

But what it actually does is;
1. create a bitmaptext object with the text "Phaser 3"
2. set the bitmaptext origin to the middle (0.5,0.5)
3. set the bitmaptext to be interactive
4. set so that when you click on it, it flips it over the middle Y (0.5,0.5) on the way to being flipped over the left (0,0)

**Comment by photonstorm** [comment]
Did you build it from the master branch? If not, it's not using a version with the fixes in (beta 0 doesn't have them)

**Comment by thenonamezz** [comment]
i haven't built it (cause frankly i have no idea how) i'm using the newest Pre-release (10 days ago it says)

**Comment by photonstorm** [comment]
Try with this build.
[dev.zip](https://github.com/photonstorm/phaser/files/5016903/dev.zip)

**Comment by thenonamezz** [comment]
Yup, that works as it should. Thanks and good job
