### ISSUE TITLE
Images not drawing when mixing with spines (v3.5beta3)

### ISSUE THREAD

**Issue by spayton** [photonstorm/phaser#5277]
## Version

* Phaser Version: v3.50.0-beta.3 (WebGL | Web Audio)

* Operating system: Win10 64bit

* Browser: Chrome 85

## Description

Problems are occuring when mixing images and spines, with the images not being seen.  Sometimes, an image that is NOT seen when it should be, can momentarity be seen on a browser refresh, as if the 1st frame render works fine.  Note, the spine used was spineboy-pro playing the 'walk' animation.

The following stages show 3 simple scenarios where a problem can be demonstrated.

stage1 - add single image to empty stage
scene: image1
expected result: to see image1
actual result: good, image1 is seen

stage2 - add a spine to previous scene
scene: image1 + spine
expected result: to see both the image1 and spine
actual result: bad, image1 is NOT seen, the spine is always seen

stage3 - add an image to previous scene
scene: image1 + spine + image2
expected result: to see both the image1, spine and image2
actual result: bad, image1 is NOT seen, the spine is always seen, image2 is always seen

stage4 - modify previous scene such that the spine is in a spineContainer
scene: image1 + spine + image2
expected result: to see both the image1, spine and image2
actual result: bad, image1 is NOT seen, spine is always seen, image2 is NOT seen

**Comment by photonstorm** [comment]
When did you last build from master? because I fixed issues relating to this on Wednesday.

**Comment by spayton** [comment]
My repository is up to date, and the timestamps on my builds are after your last checkin.  I'll rebuild and try again

**Comment by spayton** [comment]
So, after a rebuild the problem is still there.

I ran the 'dist' script to get the Phaser build and ran the 'plugin.spine.dist' script to get the spine plugin.  I used the .min versions of both builds.

If you send your beta3 builds I can try them.

**Comment by spayton** [comment]
This minimal example shows 2 problems.  My original post had another problem that this example doesn't show, maybe because I had a lot more spines being loaded.

[example.zip](https://github.com/photonstorm/phaser/files/5139308/example.zip)

**Comment by photonstorm** [comment]
I'm convinced this is working if you build the latest release of Phaser and the Spine Plugin (it needs both).

Here is my test case: http://labs.phaser.io/view.html?src=src%5Cspine%5C3.8.95%5Cspine%20scene%20test.js&v=dev

You can get the plugin and dev Phaser build from view source if you like, or just build both from the master repo.

Here's another test of the Spine plugin working across multiple Scene's running in parallel:

http://labs.phaser.io/view.html?src=src/spine/3.8.95/spine%20parallel%20scene%20test.js&v=dev

**Comment by photonstorm** [comment]
I've found a case where it fails - if you do `setDepth()` on a Spine Game Object to bring it above a normal Game Object. Without that, it renders properly, but I'll look at the depth issue now.

**Comment by photonstorm** [comment]
Ok, all tests now passing (depth, image mixture, etc) and new plugins + dev build are on the labs.

**Comment by spayton** [comment]
ok, I'll try them

**Comment by spayton** [comment]
My build still failed, the labs dev build worked, so deleted repo and checked out and rebuilt afresh and it now works.

I use sourcetree, it was showing I was checked out and up to date but now I think it had got stuck.  Today it knew there were updates available but suspiciously wouldn't fetch them.  A reboot sorted it out and then a full checkout and rebuild pretty much confirmed sourcetree as being the problem.

**Comment by spayton** [comment]
This appears to have broke again on v3.50 beta.10

**Comment by spayton** [comment]
Just checked and it's working now.  This commit fixed it 7ba1b132abd4050d93e90b20f4987c331d2c5443
