### ISSUE TITLE
[3.50 beta 11] Container destroy method bug - displayList null

### ISSUE THREAD

**Issue by FloodGames** [photonstorm/phaser#5413]
## Description
We have a container with: 
- 4 images 
- a mask

When starting a new scene, the game crashes. (seems like any container crashes it)

**Pieces of the code:**
```
export class MenuLoadingBar extends Phaser.GameObjects.Container 

//The water bar
this.progressBar = scene.add.image(0, 0, "loadingWater").setOrigin(0, 0.5)
this.add(this.progressBar)
//The mask for the waterbar
this.progressBarMask = scene.add
.image(baseX, baseY, "loadingWater")
.setOrigin(0, 0.5)
.setScale(0, 1)
this.add(this.progressBarMask)
const progressBarMask = new Phaser.Display.Masks.BitmapMask(scene, this.progressBarMask)
this.progressBar.setMask(progressBarMask)

```
    let beaverBody = scene.add
      .image(0, 0, "loadingBeaver")
      .setOrigin(0.5, 0.5)
      .setAlpha(alphaLoadingBar)
      .setDepth(DEPTH.UI + 103)

    let beaverTail = scene.add
      .image(0, 0, "loadingBeaverTail")
      .setOrigin(1.17, 0.5)
      .setAlpha(alphaLoadingBar)
      // .setScale(0.8)
      .setDepth(DEPTH.UI + 102)

    //The beaver object
    this.beaver = {
      Body: beaverBody,
      // Body: (this.beaverBody = blitter.create(this.baseX, this.baseY)),
      Tail: beaverTail,
    }
    this.add(this.beaver.Body)
    this.add(this.beaver.Tail)
```
this.scene.add.existing(this)
```

```
phaser.js:3628 Uncaught TypeError: Cannot read property 'remove' of null
    at Image.destroy (phaser.js:3628)
    at MenuLoadingBar.removeAll (phaser.js:48660)
    at MenuLoadingBar.preDestroy (phaser.js:49103)
    at MenuLoadingBar.destroy (phaser.js:3621)
    at DisplayList.shutdown (phaser.js:162062)
    at EventEmitter.emit (phaser.js:2432)
    at Systems.shutdown (phaser.js:46173)
    at SceneManager.stop (phaser.js:89726)
    at SceneManager.processQueue (phaser.js:88792)
    at SceneManager.update (phaser.js:89055)
```

![image](https://user-images.githubusercontent.com/60991890/100456097-1a6ae800-30c0-11eb-9c7b-20d4bd72d5e9.png)

## Example Test Code
Can you recommend me a default sandbox phaser ?

**Comment by photonstorm** [comment]
Yeah, I caught this earlier. Fix pushed.

**Comment by rexrainbow** [comment]
@photonstorm 
This issue is not solved completely.

From this [line](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/GameObject.js#L697):  `this.displayList.remove(this)`,  [`gameObject.displayList` set to `null`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/DisplayList.js#L140) under remove-callback. Then [next line](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/GameObject.js#L698):  `this.displayList.queueDepthSort()` won't work

Error message
```
Cannot read property 'queueDepthSort' of null
```

**Comment by sssaff** [comment]
Hi photonstorm, your comment "Fix #5413", what does that mean :-)  ? 
For me this issue is not solved yet. Is it still on the table or do you consider it closed? I just checked right now with beta 11 and I get the error.
//Thanks!

**Comment by photonstorm** [comment]
It means the issue was fixed in the referenced commit: https://github.com/photonstorm/phaser/commit/41a0c192a40aef6c967931f165030befc09b3b00

Fixes are not applied to already existing betas, they will only manifest in the beta releasing following the fix.

**Comment by sssaff** [comment]
> It means the issue was fixed in the referenced commit: [41a0c19](https://github.com/photonstorm/phaser/commit/41a0c192a40aef6c967931f165030befc09b3b00)
> 
> Fixes are not applied to already existing betas, they will only manifest in the next beta released _after_ the fix.

Ok perfect, so this means that it will be fixed in next version (beta 12)? 
(I'm sorry for maybe asking stupid question...)

**Comment by photonstorm** [comment]
Yes, this fix is available in beta 12.
