### ISSUE TITLE
activePointer does not update when using dom objects.

### ISSUE THREAD

**Issue by idrise** [photonstorm/phaser#5663]
## Version

* Phaser Version:
3.54.0
* Operating system:
Mac Big Sur

* Browser:
Chrome

## Description

Adding the configuration option to include ...
```
  dom: {
    createContainer: true,
  },
```
Stops the activePointer from Updating the coordinate. It does update on mouse down but only the first frame.

Without the DOM option the activePointer is updated as the mouse is moved.

## Example Test Code
```
import * as Phaser from 'phaser'

const sceneConfig: Phaser.Types.Scenes.SettingsConfig = {
  active: false,
  visible: false,
  key: 'BugTest',
}

export class BugTest extends Phaser.Scene {
  private text: Phaser.GameObjects.Text
  constructor() {
    super(sceneConfig)
  }

  public create(): void {
    const scene = this

    this.text = this.add.text(100, 100, `${this.input.activePointer.worldX}`, {
      color: '#ffffff',
    })
  }
  update() {
    this.text.setText(`${this.input.activePointer.worldX}`)
  }
}

const gameConfig: Phaser.Types.Core.GameConfig = {
  title: 'BugTest',

  type: Phaser.AUTO,
  width: 1920,
  height: 1080,
  scale: {
    mode: Phaser.Scale.FIT,
    autoCenter: Phaser.Scale.CENTER_BOTH,
    width: 1920,
    height: 1080,
  },
  
  scene: BugTest,
  pixelArt: true,
  physics: {
    default: 'arcade',
    arcade: {
      debug: true,
    },
  },
  // Commenting out the the next two keys causes the bug to appear.
  dom: {
    createContainer: true,
  },
  parent: 'game',
  backgroundColor: '#000000',
}

export const game = new Phaser.Game(gameConfig)
window.addEventListener('resize', () => {
  game.scale.refresh()
})
```

**Comment by rollinsafary-inomma** [comment]
just saw that I've this issue too

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).

**Comment by rollinsafary-inomma** [comment]
@photonstorm I've installed phaser from git and the bug stills there.

**Comment by rollinsafary-inomma** [comment]
@idrise I was using dragging and solved this issue this way

```typescript
protected onDragStart(pointer: Phaser.Input.Pointer):void {
 this.scene.game.domContainer.style.setProperty('pointer-events', 'none');
//...
}

protected onDragEnd(pointer: Phaser.Input.Pointer):void {
 this.scene.game.domContainer.style.removeProperty('pointer-events');
//...
}
```

This means, that my dom components will stop handling the pointer-events while dragging and will start after the drag ends.

**Comment by photonstorm** [comment]
> @photonstorm I've installed phaser from git and the bug stills there.

You downloaded the master branch and rebuilt it? If not, it isn't using 3.55.

**Comment by rollinsafary-inomma** [comment]
no, will try tomorrow with a rebuild, thanks for that note!
